### ISSUE TITLE
Not update

### ISSUE THREAD

**Issue by Sornkarn** [fishboard-app/task#11]
**GameFi Name**
'Bomb crypto'

**Describe the bug**
'Last couple of coin selling not update'

**Transaction**
please provide issue transactions.
'Dont know where to find transaction but here is my address: 0x0F85c62b53bC15B552a459f78cc936849cd7564a'

**Expected behavior**

ROI should have been update with last couple of sold coins.

**To Reproduce**

**Screenshots (OPTIONAL)**

**Additional context (OPTIONAL)**

**Comment by M0cKuPC0dE** [comment]
Accept Bug/Issue

After Random Scan 0x0F85c62b53bC15B552a459f78cc936849cd7564a interactions with 0x00e1656e45f18ec6747f5a8496fd39b50b38396d found some bcoin reward holder  not list in V0.0.2-ALPHA

**Comment by M0cKuPC0dE** [comment]
Example Tx
https://bscscan.com/tx/0x6b78c64bf83a132a12851bc5031ddaf67d195e1ded44716e08b12991fdb99036
reward holder 0xcce65eaa7d012d56cc29c3c1dd59db8149734637


https://bscscan.com/tx/0x46270763a4b522b75e529f2ca6326bae5d467541eb34257b6c613534b2d2c454
reward holder : 0x966d1cca4cf740ed9056bab436f1e40ecd759aef


https://bscscan.com/tx/0xf7d77cdb816e6a1c64d19f794758b42612c36f493e5a7e53df6a3696b9cea709
reward holder : 0xfa6bce1c7bbe759567f3b0211f3f695d340a888c


https://bscscan.com/tx/0xb440c15cb1ef94b0f130e097df56dc8390463af87d331b3ad3e18422761625e3
reward holder : 0xb6571bd589422440141f760f45764b1618af246e


MISSING REWARD HOLDER AFTER SCAN
'0x124d77791d42d17185ffac079a653e9e82a6f0b9',
'0x966d1cca4cf740ed9056bab436f1e40ecd759aef',
'0xfa6bce1c7bbe759567f3b0211f3f695d340a888c',
'0xb6571bd589422440141f760f45764b1618af246e

**Comment by M0cKuPC0dE** [comment]
**Reward holder relation**

0x291b1757d107c1851411aa297ba6046e02d4e2c3 transaction over 100k can not full track
- 0x966d1cca4cf740ed9056bab436f1e40ecd759aef *
- 0x52b76d0937132144ec27a591ed0876b77926778d
   - 0x124d77791d42d17185ffac079a653e9e82a6f0b9 *
- 0xb6571bd589422440141f760f45764b1618af246e
   - 0x966d1cca4cf740ed9056bab436f1e40ecd759aef *

0x52d2124ab6e2aa2886751c8424bc61a51f1e2ed4 transaction over 100k can not full track
- 0x124d77791d42d17185ffac079a653e9e82a6f0b9 *
- 0xfa6bce1c7bbe759567f3b0211f3f695d340a888c
  - 0xcce65eaa7d012d56cc29c3c1dd59db8149734637

**Comment by M0cKuPC0dE** [comment]
Thank you, @kismatkhan , we are update new bcoin reward holder by reward holder relations that our found from last scan,
