### ISSUE TITLE
Show wrong value of transaction

### ISSUE THREAD

**Issue by Sornkarn** [fishboard-app/task#12]
**GameFi Name**
'Cooper planet'

**Describe the bug**
'It show value'

**Transaction**
please provide issue transactions.
'https://bscscan.com/tx/0x63c8b63f5ecf87a2235b91350e927665d6055a76d64975698a3834d30d3ab3b1

https://bscscan.com/tx/0xbd1fd1553bc7b6fdeb807ecfbacea23725518eb0c4f9eff0824027bd055682e5

'

**Expected behavior**

Show correct value of the transaction

**To Reproduce**

**Screenshots (OPTIONAL)**

**Additional context (OPTIONAL)**

**Comment by M0cKuPC0dE** [comment]
Accept Bug/Issue

- PCv2 SFO/BNB LP Not provide correct price.
- Reproduce in V0.0.2-ALPHA

**Comment by M0cKuPC0dE** [comment]
Fixing by change LP to SFO/USDT for hight volume liquidity

**Comment by M0cKuPC0dE** [comment]
Thank you @kismatkhan for issue report, we has fixed price issue by retrieve price from SFO/USDT LP.
