### ISSUE TITLE
I am not sure how to contact you. I am interested in your Fishboard.app

### ISSUE THREAD

**Issue by mppulse** [fishboard-app/task#16]
Hi

My name is Tada from Thailand, I am interested in your project. I don't know how to contact you. 
I am interesting and would like to deal with you if you would like to sell your project.

You can contact me at pisit.moo@gmail.com or neorush2002@gmail.com

**Comment by M0cKuPC0dE** [comment]
@mppulse We do project for enjoyment and want to share them; I don't believe my work is valuable enough to trade, but we are flattered that you are interested in it.
