### ISSUE TITLE
can't get any game data

### ISSUE THREAD

**Issue by vyrs** [fishboard-app/task#18]
**GameFi Name**
All

**Describe the bug**
it is not able to fetch the data of any game, it seems cors problem

**Screenshots (OPTIONAL)**
![image](https://user-images.githubusercontent.com/33791729/147714344-99d09877-5332-4847-9f7e-05f984824d1f.png)

**Comment by yoogoojupi** [comment]
how to solve it

**Comment by M0cKuPC0dE** [comment]
@vyrs @yoogoojupi thank you for report, our loadbalance has limit number of request problem. now all is fixed.
