### ISSUE TITLE
Funding stat show wrong in Bpmb crypto

### ISSUE THREAD

**Issue by Sornkarn** [fishboard-app/task#7]
**GameFi Name**
'BombCrypto'

**Describe the bug**
'The sum of funding in one of account show wrong. I invest only 120$ but it show 1600$ now.'

**Transaction**
please provide issue transactions.
'https://bscscan.com/tx/0x5a56df77dd164ebeb865aa39334550d699a7ec487bdaae6cad26d215c5ef02d5'

**Expected behavior**
Correct the funding stat.

**To Reproduce**

**Screenshots (OPTIONAL)**

**Additional context (OPTIONAL)**

**Comment by M0cKuPC0dE** [comment]
**Accept Bug/Issue**
- Issue when fetch liquid provider PCv2 BCOIN/BNB LP for price at time of transaction....
- Reproduce in V0.0.2-ALPHA

**Comment by M0cKuPC0dE** [comment]
**Action Reproduce**

Action variable
- Tx reproduce : 0x5a56df77dd164ebeb865aa39334550d699a7ec487bdaae6cad26d215c5ef02d5
- Time at transaction query to LP : 2021-10-16T14:35:18.000Z
- LP : PCv2 BCOIN/BNB LP

PCv2 BCOIN/BNB LP 1min
- Open Price : 15.808721156 USD
- Close Price : 15.686283693 USD
```json
[
    {
        "open": 0.03412712271481236,
        "close": 0.033863265868677016,
        "high": 0.03448897201912528,
        "low": 0.0037723513707440407,
        "volume": 71.36719370228764,
        "count": 6,
        "time": "2021-10-15T16:11:00.000Z",
        "baseOpen": 463.230413185852,
        "baseClose": 463.2241838046981,
        "baseHigh": 465.76808761623715,
        "baseLow": 463.18272539621927
    }
```

PCv2 BCOIN/BNB LP 15min
- Open Price : 1.75865267975 USD
- Close Price : 15.7238037279 USD
```json
[
    {
        "open": 0.0037723513707440407,
        "close": 0.03393745824015241,
        "high": 0.03448897201912528,
        "low": 0.0037723513707440407,
        "volume": 71.36719370228764,
        "count": 6,
        "time": "2021-10-15T16:00:00.000Z",
        "baseOpen": 466.19535321791096,
        "baseClose": 463.31707037702546,
        "baseHigh": 466.42124133573634,
        "baseLow": 463.0408987851999
    }
]
```

PCv2 BCOIN/BNB LP 30min
- Open Price  : 1.75864414708 USD
- Close Price : 15.6642973761 USD
```json
[
    {
        "open": 0.0037723513707440407,
        "close": 0.03393745824015241,
        "high": 0.03448897201912528,
        "low": 0.0037723513707440407,
        "volume": 71.36719370228764,
        "count": 6,
        "time": "2021-10-15T16:00:00.000Z",
        "baseOpen": 466.19309132136925,
        "baseClose": 461.5636582212995,
        "baseHigh": 466.42124133573634,
        "baseLow": 461.5387817288998
    }
]
```

**Confirm BCOIN/BNB LP Provide Wrong Price 2021-10-15 to 2021-10-17 UTC **

**Comment by M0cKuPC0dE** [comment]
**Action Reproduce**

Action variable
- Tx reproduce : 0x5a56df77dd164ebeb865aa39334550d699a7ec487bdaae6cad26d215c5ef02d5
- Time at transaction query to LP : 2021-10-16T14:35:18.000Z
- LP : PCv2 BCOIN/BUSD LP

PCv2 BCOIN/BUSD LP 1min
- Open Price : 0.9554539392646999 USD
- Close Price : 0.9553296809857418 USD
```json
[
    {
        "open": 0.9554539392646999,
        "close": 0.9553296809857418,
        "high": 0.9554539392646999,
        "low": 0.9505200590976564,
        "volume": 65.58078783140186,
        "count": 5,
        "time": "2021-10-16T14:35:00.000Z",
        "baseOpen": 1,
        "baseClose": 1,
        "baseHigh": 1,
        "baseLow": 1
    }
]
```

PCv2 BCOIN/BUSD LP 15min
- Open Price : 0.9518440800324846 USD
- Close Price : 0.9370326363936486 USD
```json
[
    {
        "open": 0.9518440800324846,
        "close": 0.9370326363936486,
        "high": 0.9599010543733775,
        "low": 0.9370326363936486,
        "volume": 7788.602271476319,
        "count": 128,
        "time": "2021-10-16T14:30:00.000Z",
        "baseOpen": 1,
        "baseClose": 1,
        "baseHigh": 1,
        "baseLow": 1
    }
]
```

PCv2 BCOIN/BUSD LP 30min
- Open Price : 0.9518440800324846 USD
- Close Price : 0.9400804876537356 USD
```json
[
    {
        "open": 0.9518440800324846,
        "close": 0.9400804876537356,
        "high": 0.9599010543733775,
        "low": 0.9239763064521792,
        "volume": 17706.349372469023,
        "count": 240,
        "time": "2021-10-16T14:30:00.000Z",
        "baseOpen": 1,
        "baseClose": 1,
        "baseHigh": 1,
        "baseLow": 1
    }
]
```

**BCOIN/BUSD LP Provide Correct Price In all Timeline**
Fixing by change LP to BCOIN/BUSD

**Comment by M0cKuPC0dE** [comment]
Thank you for reporting the issue, @kismatkhan. It has now been resolved.
Please agree that the pricing calculations from pancake v2 provided to us do not contain Slippage Tolerance, and that the price will be calculated based on an average price 1 minute time period.

have a good day.
